
input('\nParte 2 - Exercício 10\n'
      'Escolha o tipo de dado mais adequado para cada uma das situações abaixo\n'
      'e caso julgue necessário, explique o motivo da escolha.\n')

print('a) a população da terra')
input('Inteiro positivo\n')
print('b) a temperatura média de ontem')
input('Float positivo com duas casas decimais\n')
print('c) o nome de uma novela brasileira')
input('String\n')
print('d) a potência de uma lâmpada')
input('Float positivo com duas casas decimais\n')
print('e) a população de um município')
input('Inteiro positivo\n')
print('f) o peso de uma pessoa')
input('Float positivo com duas casas decimais\n')
print('g) a velocidade do vento na região de uma determinada usina eólica')
input('Float positivo com 4 casas decimais\n')
print('h) a altura de uma pessoa em metros')
input('Float positivo\n')
print('i) a altura de uma pessoa em centímetros')
input('Intero positivo\n')
print('j) a cotação do dólar em reais')
input('Float positivo com duas casas decimais\n')
print('k) pontuação de um time em um jogo de basquete')
input('Inteiro positivo\n')
print('l) o preço de uma TV')
input('Float positivo com duas casas decimais\n')
print('m) o salário de um funcionário')
input('Float positivo com duas casas decimais\n')
print('n) o número de pernas de um animal')
input('Inteiro positivo\n')
print('o) o preço de um automóvel')
input('Float positivo com duas casas decimais\n')